on:
  pull_request:
    types: [opened, synchronize]
jobs:
  evaluator_job:
    runs-on: ubuntu-18.04
    name: Evaluator job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: '12'
      - name: Stylelint analysis step
        uses: betrybe/stylelint-linter-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: ESlint analysis step
        uses: betrybe/eslint-linter-action@v2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Evaluator step
        id: evaluator
        uses: betrybe/cypress-evaluator-action@v5
        with:
          repository-test-name: 'betrybe/sd-0x-project-trivia-react-redux-tests'
          repository-test-branch: 'master'
          npm-start: true
      - name: Store evaluation step
        uses: betrybe/store-evaluation-action@v2
        with:
          evaluation-data: ${{ steps.evaluator.outputs.result }}
          environment: production
          pr-number: ${{ steps.evaluator.outputs.pr-number }}
